apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    app: application
spec:
  type: NodePort
  selector:
    app: application
  ports:
    - protocol: HTTP
      port: 8010
      name: http

