apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    app: application
spec:
  replicas: 1
  template:
    metadata:
      name: application
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: antonarhipov/app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: application
---
