apiVersion: v1
kind: ReplicationController
metadata:
  name: application
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: antonarhipov/app:latest
          ports:
            - containerPort: 8010
          livenessProbe:
            httpGet:
              port: 80
              path: /health
            initialDelaySeconds: 30
            timeoutSeconds: 1

