name: CI

on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: docker://openjdk
    - name: Run a one-line script
      run: ./gradlew clean test
